Print the dependencies in plaintext tree in commander.js
jfrog/nuget-deps-tree pull request #35
Opened 2024-04-26 00:22 UTC by younthu

- [ ] All [tests](https://github.com/jfrog/nuget-deps-tree#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----
`nuget-deps-tree [path to sln file]`, it will print dependencies in json.

or

`nuget-deps-tree --text [path to sln file]`, it will print dependencies in plain text as below:

![plainTextFormat](https://github.com/jfrog/nuget-deps-tree/assets/2912431/86d47733-d40c-4132-bc44-eda887cf08ca)

2024-04-26 02:16 UTC, younthu commented
I have read the CLA Document and I hereby sign the CLA

2024-04-29 07:43 UTC, younthu commented
Anyone can help to review this please?

2024-05-01 14:50 UTC, RobiNino requested changes
Thank you very much for your contribution!
I'd appreciate if you could add `"bin/**/*.ts"` to the `format` script in `package.json`, then run `npm run format`.
Thanks!

2024-05-01 14:50 UTC, RobiNino commented on bin/command.ts
> +  .argument("<sln>", "solution file name")
```suggestion
  .argument("<sln>", "solution file path")
```

2024-05-19 07:30 UTC, RobiNino approved these changes

2024-05-19 07:31 UTC, merged

2024-05-19 08:51 UTC, RobiNino commented
Thanks again @younthu !
Version 0.4.0 is now released with your new feature.